---
title: "sandbox"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
alpha <- 20 
beta <- 20

x <- seq(0, 1, .001)
y <- dbeta(x, alpha, beta)

data.frame(x, y) %>%
    ggplot(aes(x, y)) +
    geom_line()
```

```{r fig.height=6, fig.width=9}
beta_dist__prior_successes <- 82
beta_dist__prior_trials <- 301
    
beta_dist__additional_successes <- 100
beta_dist__additional_trials <- 300

prior_alpha <- beta_dist__prior_successes
prior_beta <- beta_dist__prior_trials - beta_dist__prior_successes

new_alpha <- prior_alpha + beta_dist__additional_successes
new_beta <- prior_beta + (beta_dist__additional_trials - beta_dist__additional_successes)

distros <- data_frame(a = c(prior_alpha, new_alpha),
           b = c(prior_beta, new_beta)) %>%
  group_by(a, b) %>%
  do(data_frame(x = seq(0, 1, .001), y = dbeta(x, .$a, .$b))) %>%
  mutate(Parameters = paste0("\u03B1 = ", a, ", \u03B2 = ", b)) %>%
  ungroup() %>%
  mutate(Parameters = factor(Parameters, levels = unique(Parameters)))


min_x <- min(c(qbeta(0.01, prior_alpha, prior_beta), qbeta(0.01, new_alpha, new_beta)))
max_x <- max(c(qbeta(0.99, prior_alpha, prior_beta), qbeta(0.99, new_alpha, new_beta)))

prior_expected_value <- prior_alpha / (prior_alpha + prior_beta)
new_conversion_rate <- beta_dist__additional_successes / beta_dist__additional_trials
new_expected_value <- new_alpha / (new_alpha + new_beta)

ggplot(data=distros, aes(x, y, color = Parameters)) +
    geom_line() +
    geom_vline(xintercept = prior_expected_value, linetype='dotted', color='red', size=1) +
    geom_vline(xintercept = new_expected_value, linetype='dotted', color='#00BFC4', size=1) +
    geom_vline(xintercept = new_conversion_rate, linetype='dotted', color='black', size=1) +
    scale_x_continuous(breaks = seq(0, 1, 0.01)) +
    coord_cartesian(xlim=c(min_x, max_x)) +
    labs(title='Prior (red) and updated (blue) probability distributions',
         x="Conversion Rates",
         y="Density of beta",
         caption = paste("\nPrior Expected Value (red):", round(prior_expected_value, 3),
                         "\nNew Expected Value (teal):", round(new_expected_value, 3),
                         "\nNew Conversion Rate (black):", round(new_conversion_rate, 3)))
```

```{r}
binomial_dist__num_observations <- 1000
binomial_dist__probability <- 0.3

x <- 0:binomial_dist__num_observations
y <- dbinom(x,
            size=binomial_dist__num_observations,
            prob=binomial_dist__probability)

expected_value <- binomial_dist__num_observations * binomial_dist__probability

threshold <- 0.0001
data.frame(x, y) %>%
    filter(y > threshold & y < (1 - threshold)) %>%
    ggplot(aes(x, y)) +
    geom_bar(stat = 'identity') +
    geom_vline(xintercept=expected_value, linetype='dotted', color='red', size=1) +
    labs(title=paste0("Binomial Distribution (", binomial_dist__num_observations, ":", binomial_dist__probability, ")"),
         subtitle = paste("Expected Value:", round(binomial_dist__num_observations * binomial_dist__probability, 1)), 
         x="Observations",
         y="Probability")
```



```{r}
beta_dist__prior_successes <- 82
beta_dist__prior_trials <- 301
    
beta_dist__additional_successes_a <- 80
beta_dist__additional_trials_a <- 300

beta_dist__additional_successes_b <- 100
beta_dist__additional_trials_b <- 300

prior_alpha <- beta_dist__prior_successes
prior_beta <- beta_dist__prior_trials - beta_dist__prior_successes

new_alpha_a <- prior_alpha + beta_dist__additional_successes_a
new_beta_a <- prior_beta + (beta_dist__additional_trials_a - beta_dist__additional_successes_a)

new_alpha_b <- prior_alpha + beta_dist__additional_successes_b
new_beta_b <- prior_beta + (beta_dist__additional_trials_b - beta_dist__additional_successes_b)


alpha_vector <- c(prior_alpha, new_alpha_a, new_alpha_b)
beta_vector <- c(prior_beta, new_beta_a, new_beta_b)
distros <- data_frame(alpha = alpha_vector,
                      beta = beta_vector,
                      group = c("Prior", "A", "B")) %>%
    group_by(alpha, beta, group) %>%
    do(data_frame(x = seq(0, 1, .001))) %>%
    ungroup() %>%
    mutate(y = dbeta(x, alpha, beta),
           Parameters = factor(paste0(group, ": alpha= ", alpha, ", beta= ", beta)))

x_min <- min(qbeta(0.001, alpha_vector, beta_vector))
x_max <- max(qbeta(0.999, alpha_vector, beta_vector))

x_axis_spread <- 1#beta_dist__min_max[2] - beta_dist__min_max[1]
x_axis_break_steps <- 0.05

if(x_axis_spread <= 0.15) {

    x_axis_break_steps <- 0.01

} else if(x_axis_spread <= 0.5) {

    x_axis_break_steps <- 0.02
}

library(scales)
custom_colors <- rev(hue_pal()(3))

beta_dist__show_prior_distribution <- TRUE
if(!beta_dist__show_prior_distribution) {

    distros <- distros %>%
        filter(!str_detect(Parameters, "Prior"))
    
    custom_colors <- custom_colors[1:2]
}

a_cred_low <- qbeta(0.025, new_alpha_a, new_beta_a)
a_cred_high <- qbeta(0.975, new_alpha_a, new_beta_a)

b_cred_low <- qbeta(0.025, new_alpha_b, new_beta_b)
b_cred_high <- qbeta(0.975, new_alpha_b, new_beta_b)

a_cr_simulation <- rbeta(1e6, new_alpha_a, new_beta_a)
b_cr_simulation <- rbeta(1e6, new_alpha_b, new_beta_b)
percent_of_time_b_wins <- mean(b_cr_simulation > a_cr_simulation)

ggplot(data=distros, aes(x, y, color = Parameters)) +
    geom_line() +
    geom_area(aes(fill=Parameters, group=Parameters), alpha=0.3, position = 'identity') +
    scale_x_continuous(breaks = seq(0, 1, x_axis_break_steps)) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
    geom_errorbarh(aes(xmin = a_cred_low, xmax = a_cred_high, y = -1), height = 2, color = custom_colors[1], alpha=0.3) + 
    geom_errorbarh(aes(xmin = b_cred_low, xmax = b_cred_high, y = -2), height = 2, color = custom_colors[2], alpha=0.3) + 
    coord_cartesian(xlim=c(x_min, x_max)) +
    labs(title='Prior (red) and updated (blue) probability distributions',
         x="Conversion Rates",
         y="Density of beta",
         caption=paste0("With the given probability distributions, if we do 1 million simulations,\nB is better than A ",
                        round(percent_of_time_b_wins * 100, 1), "% of the time")) +
    scale_fill_manual(values=custom_colors) +
    scale_color_manual(values=custom_colors)


alpha_vector

beta_vector

data.frame(distribution=c())
    
```

```{r}
sim_of_sims <- map_dbl(1:100, ~ {
    
    a_cr_simulation <- rbeta(1e6, new_alpha_a, new_beta_a)
    b_cr_simulation <- rbeta(1e6, new_alpha_b, new_beta_b)
    sim_1 <- mean(b_cr_simulation > a_cr_simulation)
    sim_1
    
    a_cr_simulation <- rbeta(1e5, new_alpha_a, new_beta_a)
    b_cr_simulation <- rbeta(1e5, new_alpha_b, new_beta_b)
    sim_2 <- mean(b_cr_simulation > a_cr_simulation)
    sim_2
    
    
    abs(sim_1 - sim_2)
})

max(sim_of_sims)
```


































































